#!/bin/sh
module="chardev_test"
device="chardev_test"
mode="664"

#echo "Remove device from /dev"
#rm -f /dev/${device}

echo "Remove module"
/sbin/rmmod ./test.ko

echo "Install module"
/sbin/insmod ./test.ko

#major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)

#echo "Install device to /dev"
#mknod /dev/${device} c $major 0


